
QUESTION = """
<TASK>
Trajectory analysis task:{task}
Please choose proper model to do the {task}.Please make the choice based on CHARACTERISTICS OF MODEL and memory to get a better result for {task}. \
You should solve the task with interleaving Thought, Action and Observation steps. 
<CHARACTERISTICS OF MODEL>
{model_characteristics}

"""
THOUGHT = """
In Thought step,you should reason how to choose a proper model to get a better result for {task}.Please consider following aspects:
1.The abstract description of the model
2.The experiment result and compariation result with other baseline models
According to above aspects,please first learn experiences from MEMORY, then make plan for the action step.Please use the sentence structure 'Firstly... Then... Lastly'.Let's think step by step.
Thought:\n
"""
ACTION = """
In Action step, you should consider the Thought step in SCRATCHPAD, and give the model name you choose.
Please directly output the model name.
Action:\n
"""
MODEL_DESCRIPTION = {
    # 	RNN	FPMC LLM-MobLIMP
    "ActSTD":"""
    ActSTD proposes a novel framework based on Generative Adversarial Imitation Learning (GAIL) for generating artificial activity trajectories that preserve the fidelity and utility of real-world data. 
    The key innovation of this framework lies in its use of neural differential equations to model the continuous-time spatiotemporal dynamics underlying observed activities. 
    This enables the framework to effectively capture complex spatiotemporal dependency transition patterns, addressing the inherent randomness and sparsity issues of irregularly sampled activities. 
The paper utilizes two real-world datasets for experiments: a mobile network operator dataset and the Foursquare dataset.
    """,
    "FPMC":"""
    FPMC combines the strengths of Matrix Factorization (MF) and Markov Chain (MC) models for next-basket recommendation. 
    The method learns a personalized transition matrix for each user, rather than using a shared transition matrix, thereby capturing sequential effects (through the transition matrix) and long-term user preferences (through personalization). 
    Experimental results show that FPMC outperforms matrix factorization and non-personalized Markov chain methods on a real-world e-commerce dataset. 
    The advantage of FPMC is more pronounced on sparse datasets, as the factorization model can fill in the sparse transition matrix and prevent overfitting.
    """,
    "GETNext":"""
    GETNext is a Graph-Enhanced Transformer model for next POI recommendation.
    It constructs a global trajectory flow graph to capture common transition patterns of visit sequences between POIs and encoding them into POI embeddings using Graph Convolutional Networks;
    It integrated global transition patterns, user general preferences, user short-term trajectories, and spatio-temporal contexts using a transformer-based framework.
    """,
    "GraphMM":"""
    GraphMM is a deep learning-based map matching method.
    It utilizes a vehicle trajectory dataset collected by Tencent Maps, covering an area of 8.69 km × 7.67 km in northeastern Beijing.
    Under both transductive and inductive settings, GraphMM significantly outperforms industrial-level Hidden Markov Models (HMM) and state-of-the-art Sequence-to-Sequence (Seq2Seq) methods in terms of trajectory matching accuracy and path similarity metrics.
    Compared to the best baseline method, MTrajRec, GraphMM improves accuracy by 9.08%, 6.89%, and 14.71%, and path similarity by 6.25%, 3.32%, and 6.39%, respectively.
    """,
    "DeepMM":"""
    DeepMM is a deep learning-based map matching method.
    An effective trajectory data augmentation technique was proposed to expand the training data, improving model performance and robustness.
    It uses real vehicle trajectory data which is Tencent data, and sparse and noisy trajectory data were generated by simulating different sampling intervals and Gaussian noise.
    It outperforms traditional methods such as HMM by more than 10% in matching accuracy, particularly excelling in noisy and sparse conditions. 
    The application of data augmentation techniques also significantly enhanced model performance and reduced overfitting issues.
    """,
    "MulTTTE":"""
    MulTTTE is a multi-faceted path representation learning framework for accurate travel time estimation. 
    It use two large-scale real-world taxi trajectory datasets from Chengdu and Porto were used.
    MulT-TTE was compared with 11 baseline methods, including statistical methods, machine learning methods, and sequence-based deep learning methods.
    As a segment-based representation learning method, MulT-TTE showed more stable performance in long-distance and long-duration travel scenarios.
    """,
    "MainTUL":"""
    MainTUL is a novel Mutual Distillation Learning Network (MainTUL) to address the Trajectory-User Linking (TUL) problem with sparse check-in mobility data.
    Experimental results demonstrate that MainTUL significantly outperforms state-of-the-art baseline models on two real-world check-in mobility datasets, with an average improvement of 14.95% in Acc@1 and 14.11% in Macro-F1. 
    Compared to RNN-based models such as TULER and DeepTUL, the two trajectory encoders designed by MainTUL based on mutual distillation can more effectively capture the spatio-temporal movement patterns of user check-in trajectories.
    When compared to classical machine learning models, MainTUL also shows significant superiority over baseline models in terms of Acc@1 and Macro-F1 metrics.
    """,
    "S2TUL":"""
    S2TUL is a semi-supervised framework for the Trajectory-User Linking (TUL) task, aiming to identify users from anonymous trajectories. 
    Constructing a trajectory-level graph to model relationships between trajectories, including repetitiveness, spatial proximity, and spatiotemporal proximity.
    It Combines the two-level representations in a classification layer to predict the user of an input trajectory and Introducing a greedy trajectory-user relinking method to ensure that the linking results satisfy the time span overlap constraint.
    """,
    "DSTPP":"""
    DSTPP is a novel framework for modeling spatio-temporal point processes, demonstrating excellent performance in multiple practical applications.
    It use a synthetic dataset and three real-world datasets, covering scenarios such as earthquakes, COVID-19 spread, New York City bike-sharing, and a simulated Hawkes Gaussian mixture model process.
    DSTPP outperformed existing baseline models across various evaluation metrics, including negative log-likelihood and spatio-temporal predictive capabilities.
Compared to classical point process models with assumed parameterizations, DSTPP is better at capturing spatio-temporal dependencies, thereby enhancing modeling performance.
    """,
    "CACSR":"""
    CACSR is a novel contrastive pre-training model, designed for learning representations of check-in sequences. 
    CACSR uses Three real-world datasets: Gowalla, New York City Foursquare, and Jakarta Foursquare.
Compared to models such as LSTM, SERM, DeepMove, LSTPM, SimCSE-LP, and VaSCL-LP, CACSR-LP demonstrated superior performance in the location prediction task.
Against models like TULER, TULVAE, MoveSim, DeepTUL, SimCSE-TUL, and VaSCL-TUL, CACSR-TUL showed better performance in the trajectory-user link task.
    """,
    "DeepMove":"""
    DeepMove is a model for predicting human mobility behavior from long and sparse trajectories. 
    the model using three real-world mobility datasets, including Foursquare check-in data, mobile app location data, and call detail records from a telecommunications operator. 
    DeepMove can effectively capture the complex sequential transition patterns and multi-level periodicity of human mobility behavior.
    The results of experiments on different user groups indicate that DeepMove achieves greater performance improvements when predicting non-routine users with higher mobility entropy, exploration ratios, and movement ranges compared to baseline models. This validates the effectiveness of DeepMove in leveraging long-term historical trajectories to capture latent periodic patterns.
        """,
    "DPLink":"""
    DPLink is a model for TUL(trajectory user linking) task. 
    It is an end-to-end deep learning based framework, to complete the user identity linkage task for heterogeneous mobility data collected from different services with different properties. 
DPLink model outperforms the baseline model by more than 15% on two real-world datasets.
Through its innovative pre-training strategy and model design, significantly outperforms the baseline model on user identity linking tasks, demonstrating its advantages in handling heterogeneous mobile data.
    """,
    "DeepTTE":"""
        DeepTTE is a model for TTE(travel time estimitation) task.
        It includes a spatial-temporal component that leverages convolutional neural networks and LSTMs to capture the spatial correlations and temporal dependencies in the raw GPS sequences .
        The proposed DeepTTE model further outperforms RnnTTE, with error rates of only 11.89% and 10.92% on the two datasets. 
        """,
    "GMVSAE":"""
    GM-VSAE is for online anomalous trajectory detection. 
    It used two trajectory datasets, namely the Porto and Beijing datasets. 
   Compared to existing baseline models (e.g., T-DBSCAN, iBAT, DBTOD-embed, SAE, VSAE), GM-VSAE achieved better results in terms of the PR-AUC (Precision-Recall Area Under Curve) metric for anomaly detection. 
        """,
    "TrajBERT":"""
TrajBERT is a BERT-based trajectory recovery model, which can effectively recover dense trajectories from sparse implicit trajectories. 
It uses three real-world trajectory datasets, including Geolife, CDRTraj, and T-drive, to evaluate the performance of the proposed TrajBERT model. 
The paper compares TrajBERT with 6 baseline models, including heuristic models based on prior knowledge (History and Top), deep learning-based models (Bi-STDDP, AttnMove, LSTM, and BERT).  The experimental results show that TrajBERT significantly outperforms all baseline models, with a minimum improvement of 8.2%.  This is mainly due to TrajBERT's use of cross-stage temporal refinement and spatial-temporal aware loss function, which can better capture the spatial-temporal dependencies of trajectories. 
        """
}
DATA_DESCRIPTION = {
    "gowalla":
    """
    This dataset includes long-term (about 18 months from Feb. 2009 to Oct. 2010) global-scale check-in data collected from Gowalla webset.
It contains 6,442,890 check-ins of users on 196,591 venues.
    """,
    "standard":
    """
    This dataset contains check-ins in NYC and Tokyo collected for about 10 month (from 12 April 2012 to 16 February 2013). It contains 227,428 check-ins in New York city.
    """,
    "foursquare":
    """
    This dataset includes long-term (about 18 months from April 2012 to September 2013) global-scale check-in data collected from Foursquare webset.
It contains 33,278,683 checkins by 266,909 users on 3,680,126 venues (in 415 cities in 77 countries). 
    """,
    "brightkite":
    """
    This dataset contains long-term (from Apr. 2008 to Oct. 2010) global-scale check-in data collected from BrightKite webset. It contains 4,491,143 check-ins by 58228 users.
    """,
    "chengdu":"""It records nearly 100 million statistical data of more than 13,000 taxis. The date of statistical collection is from August 3 to August 30, 2014, 
    and the specific time is from 6:00:00 to 23:59:59. The data set records the license plate number, latitude, longitude, passenger status (passengers are 1, no passengers are 0), date and time information.""",
    "Porto":"""Describes the full-year trajectories of all 442 taxis operating in the city of Porto, Portugal (from July 1, 2013 to June 30, 2014). These taxis 
    are operated through taxi dispatch centers using mobile data terminals installed in the vehicles. This dataset can help learn basic methods in the field of geospatial analysis and trajectory processing""",
    "T-Drive":"""It contains GPS trajectories of 10,357 taxisin Beijing [49]. Each taxi’s location is sampled every177 seconds on average.""",
    "cdr_traj":"""This dataset encompasses anonymizedCall Detail Record (CDR) trajectories of 9,995 userswithin a Chinese city from December 1st to De-cember 29th, 2021.""",
    "Beijing_taxi_sample":"""3,384,847 trajectories, 10,039 taxis, sampling rate 60 seconds, covering an area of 29.9km x 29.5km, grid size 128 x 128.""",
    "Geolife":"""Originating from the Microsoft ResearchAsia Geolife project, Geolife was amassed from 182global users between April 2007 and August 2012."""
}